feature/social share
meetalva/website pull request #25
Opened 2017-12-20 21:46 UTC by lucoel

this closes #9 and closes #10

2017-12-20 21:56 UTC, tilmx requested changes
On mobile devices the share-section looks broken :-(

2017-12-20 21:56 UTC, tilmx commented on index.html
> +              <a class="social-item twitter" href="https://twitter.com/home?status=Alva%20is%20a%20radically%20new%20design%20tool%20that%20enables%20cross-functional%20teams%20to%20design%20digital%
We should use meetalva.io as a domain, not meetalva.github.io

2017-12-20 21:56 UTC, tilmx commented on index.html
> +              <a class="social-item facebook" href="https://www.facebook.com/sharer/sharer.php?u=https%3A//meetalva.github.io/" target="_blank">Share on Facebook</a>
same here... meetalva.io

2017-12-20 21:56 UTC, tilmx commented on index.html
> +              <a class="social-item twitter" href="https://twitter.com/home?status=Alva%20is%20a%20radically%20new%20design%20tool%20that%20enables%20cross-functional%20teams%20to%20design%20digital%
And we should use the new text (from the hero: Meet Alva, 
a radically new digital design tool built for cross-functional product teams.)

2017-12-20 22:05 UTC, lucoel commented
my bad, fix is coming!

2017-12-20 23:04 UTC, tilmx commented
Zwei Dinge sind mir noch aufgefallen:
- [ ] Kannst du noch ein wenig mehr Space links/rechts von den Social buttons einbauen?
- [ ] Der Tweet startet mit einem punkt vor @meetalva – kann man den rausmachen?

2017-12-20 23:20 UTC, tilmx approved these changes

2017-12-21 02:11 UTC, tilmx commented
now duplicate of #27

2017-12-21 02:11 UTC, closed without merging