Feat/sites notice
meetalva/website pull request #70
Opened 2018-02-15 17:37 UTC by markusoelhafen

2018-02-16 10:51 UTC, tilmx submitted a review, later dismissed

2018-02-20 21:34 UTC, Alexpeschel requested changes

2018-02-20 21:34 UTC, Alexpeschel commented on lib/legalnotice.html
> +		<a class="legallink" href="/legalnotice.html" target="_blank">Legal notice</a> <a class="legallink" href="/privacypolicy.html" target="_blank">Privacy policy</a>
same as above

2018-02-20 21:34 UTC, Alexpeschel commented on lib/privacypolicy.html
> +		<a class="legallink" href="/legalnotice.html" target="_blank">Legal notice</a> <a class="legallink" href="/privacypolicy.html" target="_blank">Privacy policy</a>
same as above

2018-02-20 21:34 UTC, Alexpeschel commented on lib/index.html
> +		<a class="legallink" href="/legalnotice.html" target="_blank">Legal notice</a> <a class="legallink" href="/privacypolicy.html" target="_blank">Privacy policy</a>
is there a reason for using target blank?
otherwise please remove it :)

2018-02-23 09:39 UTC, Alexpeschel approved these changes

2018-02-23 09:57 UTC, merged